filename: "C:\\dev\\Bachelor\\merlin-formulas\\wingas\\merlin-clauseset420509740828757424.txt"
# "C:\\dev\\Bachelor\\test-formulas\\test_amo.txt"
output:
  print_progress: true
  output_plots: true

ordering:
  skip_most_frequent_var: true