#filename: "C:\\dev\\Bachelor\\merlin-formulas\\wingas\\merlin-clauseset420509740828757424.txt"
filename: "C:/dev/Bachelor/test-formulas/test_amo.txt"
output:
  print_progress: true
  output_plots: false

ordering:
  set:
    strategy: "force-modified" # none, random, size, var-frequency, force
    ascending: true # relevant only for 'size' strategy
    skip_most_frequent_var: true # relevant only for 'var-frequency' strategy
    count_all_appearances: false # relevant only for 'var-frequency' strategy
  clause:
    strategy: "none" # none, bottom-up, force
  variable:
    strategy: "force" # none, var-frequency

  enable_dynamic_ordering: true
  construction:
    formula: "dfs" # dfs, merge
    ruleset: "dfs" # dfs, merge_recursive, merge_parts
    parts_amount: 10 # relevant only for ruleset 'merge_parts' strategy
