filename: "C:\\dev\\Bachelor\\merlin-formulas\\wingas\\merlin-clauseset420509740828757424.txt"
# "C:\\dev\\Bachelor\\test-formulas\\test_amo.txt"
output:
  print_progress: true
  output_plots: true

ordering:
  set:
    strategy: "force" # none, random, size, var_frequency, force
    ascending: true # relevant only for 'size' strategy
    skip_most_frequent_var: false # relevant only for 'var_frequency' strategy
    count_all_appearances: false # relevant only for 'var_frequency' strategy

  clause:
    strategy: "force" # none, bottom_up, force
  enable_dynamic_ordering: true
  construction:
    formula: "dfs" # dfs, merge
    ruleset: "merge" # dfs, merge
    parts_amount: 10 # relevant only for ruleset 'merge' strategy
