name: tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - uses: actions/checkout@v1
      - name: Compile CUDD library
        run: cd libs/cudd-3.0.0 && ./configure && make && cd ../..
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: make
        run: cd build && make
      - name: Run test
        run: cmake-build-debug/tests/tests
